import {
  mdiArrowAll,
  mdiCalendar,
  mdiChartBar,
  mdiCheck,
  mdiClose,
  mdiCog,
  mdiContentCopy,
  mdiContentSave,
  mdiDelete,
  mdiDragVerticalVariant,
  mdiEarth,
  mdiExport,
  mdiGithub,
  mdiGoKartTrack,
  mdiHome,
  mdiInformation,
  mdiInformationBoxOutline,
  mdiMapMarker,
  mdiMenu,
  mdiPen,
  mdiPlus,
  mdiPrinter,
  mdiProgressAlert,
  mdiProgressCheck,
  mdiSpeedometer,
  mdiStar,
  mdiStarOutline,
  mdiTimer,
  mdiTrashCanOutline,
  mdiTrophyOutline,

  // Sports
  mdiBadminton,
  mdiBasketball,
  mdiBikeFast,
  mdiBoxingGlove,
  mdiBullseyeArrow,
  mdiDumbbell,
  mdiGymnastics,
  mdiHockeySticks,
  mdiKarate,
  mdiRun,
  mdiRunFast,
  mdiSkate,
  mdiSki,
  mdiSkiCrossCountry,
  mdiSoccer,
  mdiSwim,
  mdiTennis,
  mdiWalk,
  mdiYoga,
} from '@mdi/js';

export default {
  arrowAll: mdiArrowAll,
  calendar: mdiCalendar,
  chartBar: mdiChartBar,
  check: mdiCheck,
  close: mdiClose,
  cog: mdiCog,
  contentCopy: mdiContentCopy,
  contentSave: mdiContentSave,
  delete: mdiDelete,
  dragVerticalVariant: mdiDragVerticalVariant,
  earth: mdiEarth,
  export: mdiExport,
  github: mdiGithub,
  goKartTrack: mdiGoKartTrack,
  home: mdiHome,
  information: mdiInformation,
  informationBoxOutline: mdiInformationBoxOutline,
  mapMarker: mdiMapMarker,
  mdiDragVerticalVariant: mdiDragVerticalVariant,
  menu: mdiMenu,
  pen: mdiPen,
  plus: mdiPlus,
  printer: mdiPrinter,
  progressAlert: mdiProgressAlert,
  progressCheck: mdiProgressCheck,
  speedometer: mdiSpeedometer,
  star: mdiStar,
  starOutline: mdiStarOutline,
  timer: mdiTimer,
  trashCanOutline: mdiTrashCanOutline,
  trophyOutline: mdiTrophyOutline,

  // Sports
  badminton: mdiBadminton,
  basketball: mdiBasketball,
  boxing: mdiBoxingGlove,
  cycling: mdiBikeFast,
  downhill: mdiSki,
  gym: mdiDumbbell,
  gymnastics: mdiGymnastics,
  hockey: mdiHockeySticks,
  maintenance: mdiYoga,
  martialarts: mdiKarate,
  running: mdiRun,
  shooting: mdiBullseyeArrow,
  skating: mdiSkate,
  skiing: mdiSkiCrossCountry,
  soccer: mdiSoccer,
  sprint: mdiRunFast,
  swimming: mdiSwim,
  tennis: mdiTennis,
  walking: mdiWalk,
};
